#!/bin/bash

START_TOTAL=$(date +%s)

rm -rf extracted
mkdir -p extracted

cd extracted

for i in $(adb shell pm list packages -f | cut -d= -f 1 | cut -d ":" -f 2); do
    echo "Pulling $i:"
    adb pull $i
done

IN_APK_ARR=($(ls *.apk))
for f in "${IN_APK_ARR[@]}"; do
    if [ "$f" != ${f/Google/} ] || [ "$f" = "framework-res.apk" ]; then
        rm "$f"
    else
        file_name=${f/.apk/}
        mkdir $file_name
        unzip "$f" -d $file_name
        aapt dump xmltree $f AndroidManifest.xml > $file_name/$file_name.manifest.xml
        echo "$file_name" >> location.txt
        rm "$f"
    fi
done

cd ..

END_PRE_PROCESS=$(date +%s)
DIFF_PRE_PROCESS=$(($END_PRE_PROCESS - $START_TOTAL))

START_JITANA_IAC=$(date +%s)
./jitana-iac
END_JITANA_IAC=$(date +%s)

DIFF_JITANA_IAC=$(($END_JITANA_IAC - $START_JITANA_IAC))
DIFF_TOTAL=$(($END_JITANA_IAC - $START_TOTAL))

RSG=output/resource_sharing_graph.dot
RSG_SIMPLIFIED=output/resource_sharing_graph_simplified.dot
(head -n 3 $RSG && tail -n +4 $RSG | sort) | uniq > $RSG_SIMPLIFIED

echo "$DIFF_PRE_PROCESS seconds for preprocessing"
echo "$DIFF_JITANA_IAC seconds for jitana-iac"
echo "$DIFF_TOTAL seconds total"
