#!/bin/bash

if [ $# -eq 0 ]; then
    echo "usage: $0 [directory of APK files]"
    exit 1
fi

START_TOTAL=$(date +%s)

rm -rf extracted
mkdir -p extracted
cp $1/* extracted

cd extracted

for f in *.apk; do
    if [[ "$f" != *"Google"* && "$f" != "framework-res.apk" ]]; then
        out=${f/.apk/}
        apktool decode --force --no-src -o "$out" "$f" \
            && echo "$out" >> location.txt
    fi
done

rm -f *.apk

cd ..

END_PRE_PROCESS=$(date +%s)
DIFF_PRE_PROCESS=$(($END_PRE_PROCESS - $START_TOTAL))

START_JITANA_IAC=$(date +%s)
./jitana-iac
END_JITANA_IAC=$(date +%s)

DIFF_JITANA_IAC=$(($END_JITANA_IAC - $START_JITANA_IAC))
DIFF_TOTAL=$(($END_JITANA_IAC - $START_TOTAL))

./simplify-dot

echo "$DIFF_PRE_PROCESS seconds for preprocessing"
echo "$DIFF_JITANA_IAC seconds for jitana-iac"
echo "$DIFF_TOTAL seconds total"
